# Generated by Django 2.0.2 on 2020-04-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('cantidad_pedida', models.IntegerField(default=1)),
                ('entregado', models.BooleanField()),
                ('cantidad_entregada', models.IntegerField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidad')),
            ],
        ),
    ]
