# Generated by Django 2.0.2 on 2020-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200404_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(choices=[('M', 'Media'), ('B', 'Baja'), ('A', 'Alta')], default='M', max_length=15),
        ),
    ]
