# Generated by Django 2.0.2 on 2020-04-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200404_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('entregado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pedidos.Pedido'),
        ),
    ]
