# Generated by Django 3.0.5 on 2020-04-06 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200405_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
