# Generated by Django 2.0.2 on 2020-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
